### ISSUE TITLE
ctf_tantum by Sonix

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds-maps#2]
Sonix is part of the Map Working Group and the author of ctf_tantum

tantum is designed as a 4on4 map and was already tested in some matches
with some known vanilla players.
(If it's gonna be pulled you can change the name to something else)

Screenshots:
http://i.imgur.com/XaL9gnf.png
http://i.imgur.com/yz9y5wO.png
http://i.imgur.com/xHrvHCt.png

Comparison:
Latest version: http://i.imgur.com/3SgpEPK.png
First version: http://imageshack.us/a/img39/7320/screenshot2012091919333.png

map:
https://up1.ca/#RFSj3SZz5XbJ-xoZ_fnOTw

**Comment by ObaniGemini** [comment]
The map is cool, but it seems quite empty. Why not add some spikes in some places (like in some corners for example), or just add some more various terrain heights ?

- A_big_player_of_teeworlds

**Comment by Sonix-** [comment]
I've updated the first post: added new screenshots and a download link of the latest version.

The map is complete, few things left that I need help with: doodads decoration and Background colouring (I'd like to use a new color scheme, dark green, instead of the common ones).
