### ISSUE TITLE
Making kukurice one of the official survival maps

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds-maps#5]
Since it's the most fun,loved and played map used to play survival, I'd like to make it part of the official maps.
What are your thoughts?
Survival is not sur without this map :p

**Comment by msiglreith** [comment]
Initial version has been pushed (https://github.com/teeworlds/teeworlds-maps/commit/5207cac495b1f940a8cae01601d1f8accbb33cd4)
